---
seed: stripy zebra
output_dir: log/bs20/{preset}

# Average Length = 100

anchors:
- &exp_spec
  length:
    type: "Exp"
    lambda: 8
    offset: 80
    factor: 80
  budget: 130.0

incoming:
- type: "Rate"
  unit: 250
  per: 5
  bursty: true
  spec: *exp_spec

until:
  type: Time
  max: 20000

## Average Length = 200

# anchors:
# - &exp_spec
#   length:
#     type: "Exp"
#     lambda: 6
#     offset: 160
#     factor: 100
#   budget: 230.0

# incoming:
# - type: "Rate"
#   unit: 500
#   per: 5
#   bursty: true
#   spec: *exp_spec

# until:
#   type: Time
#   max: 40000

scheduler:
  type: FIFO

workers:
- batch_size: 20

presets:
  fifo: {}
  rand:
    scheduler:
      type: Random
  my:
    scheduler:
      type: My
      percentile: 0.99

  test:
    incoming:
    - type: "OneBatch"
      delay: 0.5
      n_jobs: 10
      spec: *exp_spec
    - type: "Rate"
      unit: 1.0
      per: 2
      spec: *exp_spec
    scheduler:
      type: FIFO
    until:
      type: Time
      max: 10.0

  exp:
    incoming:
      type: "OneBatch"
      delay: 0.0
      n_jobs: 200
      spec: *exp_spec
    scheduler:
      type: FIFO

logging:
  outputs:
  - enabled: true
    # the target can be term or file
    target:
      type: term
      name: stderr
      auto_switch: true
    filter:
      from_env: false
      directives: DEBUG
