---
seed: stripy zebra
output_dir: log/{preset}

presets:
  exp:
    incoming:
      type: "OneBatch"
      delay: 0.0
      n_jobs: 500
      spec:
        length:
          type: "Exp"
          lambda: 1.5
          mean: 10.0
          scale: 18.0
    scheduler:
      type: "FIFO"
      batch_size: 10

  rand:
    incoming:
      type: "OneBatch"
      delay: 0.0
      n_jobs: 500
      spec:
        length:
          mean: 10.0
          std_dev: 25.0
          scale: 18.0
          type: Exp
          lambda: 1.5
    scheduler:
      type: "Random"
