---
seed: stripy zebra
output_dir: log/{preset}

anchors:
- &exp_spec
  length:
    type: "Exp"
    lambda: 1.5
    offset: 10.0
    factor: 18.0
  budget: 200.0

presets:
  my:
    incoming:
    - type: "Rate"
      unit: 40
      per: 2
      bursty: true
      spec: *exp_spec
    scheduler:
      My:
        percentile: 99.9
    until:
      Time: 1000.0

  bursty:
    incoming:
    - type: "Rate"
      unit: 40
      per: 2
      bursty: false
      spec: *exp_spec
    scheduler:
      FIFO:
    until:
      Time: 1000.0
  test:
    incoming:
    - type: "OneBatch"
      delay: 0.5
      n_jobs: 10
      spec: *exp_spec
    - type: "Rate"
      unit: 1.0
      per: 2
      spec: *exp_spec
    scheduler:
      FIFO: {}
    until:
      Time: 10

  exp:
    incoming:
      type: "OneBatch"
      delay: 0.0
      n_jobs: 200
      spec: *exp_spec
    scheduler:
      FIFO: {}

  rand:
    incoming:
      type: "OneBatch"
      delay: 0.0
      n_jobs: 200
      spec: *exp_spec
    scheduler:
      Random: {}

logging:
  outputs:
  - enabled: true
    # the target can be term or file
    target:
      type: term
      name: stderr
      auto_switch: true
    filter:
      from_env: false
      directives: DEBUG
