---
seed: stripy zebra
output_dir: log/{preset}

anchors:
- &exp_spec
  length:
    type: "Exp"
    lambda: 1.5
    offset: 10.0
    factor: 18.0

presets:
  my:
    incoming:
    - type: "Rate"
      unit: 10.0
      per: 2
      spec: *exp_spec
    - type: "Rate"
      unit: 100.0
      per: 1
      spec:
        length:
          type: "Uniform"
          low: 150.0
          high: 200.0
    scheduler:
      type: "My"
      percentile: 99.9
    until:
      Time: 300.0

  test:
    incoming:
    - type: "OneBatch"
      delay: 0.5
      n_jobs: 10
      spec: *exp_spec
    - type: "Rate"
      unit: 1.0
      per: 2
      spec: *exp_spec
    scheduler:
      type: "FIFO"
    until:
      Time: 2.6

  exp:
    incoming:
      type: "OneBatch"
      delay: 0.0
      n_jobs: 500
      spec: *exp_spec
    scheduler:
      type: "FIFO"

  rand:
    incoming:
      type: "OneBatch"
      delay: 0.0
      n_jobs: 500
      spec: *exp_spec
    scheduler:
      type: "Random"
