---
seed: stripy zebra
output_dir: log/{preset}

anchors:
- &exp_spec
  length:
    type: "Exp"
    lambda: 1.5
    offset: 10.0
    factor: 18.0
  budget: 200.0

incoming:
- type: "Rate"
  unit: 40
  per: 2
  bursty: true
  spec: *exp_spec

until:
  type: Time
  max: 1000

scheduler:
  type: FIFO

workers:
- batch_size: 3

presets:
  fifo: {}
  rand:
    scheduler:
      type: Random
  my:
    scheduler:
      type: My
      percentile: 99.9

  test:
    incoming:
    - type: "OneBatch"
      delay: 0.5
      n_jobs: 10
      spec: *exp_spec
    - type: "Rate"
      unit: 1.0
      per: 2
      spec: *exp_spec
    scheduler:
      type: FIFO
    until:
      type: Time
      max: 10.0

  exp:
    incoming:
      type: "OneBatch"
      delay: 0.0
      n_jobs: 200
      spec: *exp_spec
    scheduler:
      type: FIFO

logging:
  outputs:
  - enabled: true
    # the target can be term or file
    target:
      type: term
      name: stderr
      auto_switch: true
    filter:
      from_env: false
      directives: DEBUG
