name: Tests

on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        #- macos-latest
        #- windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1

    - name: Run cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
